name: CTF Lean Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  test-chrome:
    name: CTF Lean Testing
    runs-on: ubuntu-latest

    env:
      BROWSER: chrome
      ENV: staging


    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set credentials based on environment
        run: |
          if [ "${{ env.ENVIRONMENT }}" == "dev" ]; then
            echo "USERNAME=${{ secrets.DEV_USERNAME }}" >> $GITHUB_ENV
            echo "PASSWORD=${{ secrets.DEV_PASSWORD }}" >> $GITHUB_ENV
          elif [ "${{ env.ENVIRONMENT }}" == "qa" ]; then
            echo "USERNAME=${{ secrets.QA_USERNAME }}" >> $GITHUB_ENV
            echo "PASSWORD=${{ secrets.QA_PASSWORD }}" >> $GITHUB_ENV
          elif [ "${{ env.ENVIRONMENT }}" == "staging" ]; then
            echo "USERNAME=${{ secrets.STAGING_USERNAME }}" >> $GITHUB_ENV
            echo "PASSWORD=${{ secrets.STAGING_PASSWORD }}" >> $GITHUB_ENV
          fi

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Run Tests (Chrome)
        run: mvn clean test -Dbrowser=${{ env.BROWSER }} -Denv=${{ env.ENV }}

      - name: Generate Allure Report
        if: always()
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report (Chrome)
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages
